version: 2
jobs:
  build:
    working_directory: /tmp/wordpress/wp-content/themes/patch
    docker:
      - image: pixelgrade/wptrunk
        environment:
          WORDPRESS_DB_HOST: 127.0.0.1
        ports:
          - 8080:80
          - 3306:3306
      - image: mysql:5.7
        environment:
          MYSQL_ROOT_HOST: "%"
          MYSQL_DATABASE: wordpress
          MYSQL_ROOT_PASSWORD: mypass
        ports: 3306:3306
    steps:
      - checkout
      - run:
          name: Add domain
          command: echo 127.0.0.1 patch.dev | tee -a /etc/hosts

      - run:
          name: Wait for mysql
          command: |
            until nc -z -v -w30 127.0.0.1 3306
            do
              echo "Waiting for database connection..."
              # wait for 2 seconds before check again
              sleep 2
            done

      - run:
          name: Create wp-config
          command: wp core config --path=/tmp/wordpress --dbname=wordpress --dbuser=root --allow-root --dbhost=127.0.0.1 --dbpass=mypass
      - run:
          name: Run WordPress core install
          command: wp core install --url=http://patch.dev --title=Test --admin_user=admin --admin_password=12345 --admin_email=test@test.com --path=/tmp/wordpress --allow-root

      - run:
          name: Run phpUnit tests
          command: cd ./tests && ls -al && phpunit

      - deploy:
          name: Deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "test" ]; then
              sh ./.circleci/deploy_test.sh
            fi
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              sh ./.circleci/deploy_production.sh
            fi

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - build:
          context: org-global
          filters:
            branches:
              only:
                - test
                - master
